// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SET3_Backend.Database;

#nullable disable

namespace SET3_Backend.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SET3_Backend.Models.ActionModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("actionType")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ActionModels");
                });

            modelBuilder.Entity("SET3_Backend.Models.BrRac", b =>
                {
                    b.Property<string>("IdRac")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrOznRac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OznNapUr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OznPosPr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRac");

                    b.ToTable("BrRac");
                });

            modelBuilder.Entity("SET3_Backend.Models.CashRegisterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Installed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CashRegisterModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 1",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 2",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 3",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 4",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 5",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 6,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 1",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 7,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 2",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 8,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 3",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 9,
                            Deleted = false,
                            Description = "Description",
                            Installed = false,
                            Name = "Register 4",
                            ShopId = 2
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tax")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CategoryModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food",
                            Tax = 0.17000000000000001
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hygiene",
                            Tax = 0.17000000000000001
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothes",
                            Tax = 0.17000000000000001
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.DeliveryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DeliveryModels");
                });

            modelBuilder.Entity("SET3_Backend.Models.ExportShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CashRegisterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExportShopModels");
                });

            modelBuilder.Entity("SET3_Backend.Models.FiscalBillModel", b =>
                {
                    b.Property<string>("IdFiscal")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JIR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RacunIdRacun")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ZaglavljeIdZag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdFiscal");

                    b.HasIndex("RacunIdRacun");

                    b.HasIndex("ZaglavljeIdZag");

                    b.ToTable("FiscalBillModels");
                });

            modelBuilder.Entity("SET3_Backend.Models.LoggingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("UserModelId");

                    b.ToTable("LoggingModels");
                });

            modelBuilder.Entity("SET3_Backend.Models.MeasuringUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MeasuringUnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeasuringUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeasuringUnitName = "Units"
                        },
                        new
                        {
                            Id = 2,
                            MeasuringUnitName = "Grams"
                        },
                        new
                        {
                            Id = 3,
                            MeasuringUnitName = "Kilograms"
                        },
                        new
                        {
                            Id = 4,
                            MeasuringUnitName = "Milliliters"
                        },
                        new
                        {
                            Id = 5,
                            MeasuringUnitName = "Liters"
                        },
                        new
                        {
                            Id = 6,
                            MeasuringUnitName = "Jars"
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderModels");
                });

            modelBuilder.Entity("SET3_Backend.Models.Porez", b =>
                {
                    b.Property<string>("IdPorez")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<double>("Osnovica")
                        .HasColumnType("float");

                    b.Property<string>("RacunIdRacun")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Stopa")
                        .HasColumnType("float");

                    b.HasKey("IdPorez");

                    b.HasIndex("RacunIdRacun");

                    b.ToTable("Porez");
                });

            modelBuilder.Entity("SET3_Backend.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarcodeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("MeasuringUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "",
                            BarcodeText = "",
                            CategoryName = "Food",
                            Deleted = false,
                            MeasuringUnit = "Kilograms",
                            Name = "Banana",
                            Price = 2.5f,
                            Quantity = 0.0,
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "",
                            BarcodeText = "",
                            CategoryName = "Hygiene",
                            Deleted = false,
                            MeasuringUnit = "Liters",
                            Name = "Tide",
                            Price = 5f,
                            Quantity = 0.0,
                            StockId = 1
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "",
                            BarcodeText = "",
                            CategoryName = "Clothes",
                            Deleted = false,
                            MeasuringUnit = "Units",
                            Name = "White shirt",
                            Price = 15f,
                            Quantity = 0.0,
                            StockId = 1
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "",
                            BarcodeText = "",
                            CategoryName = "Food",
                            Deleted = false,
                            MeasuringUnit = "Units",
                            Name = "Chocolate",
                            Price = 2f,
                            Quantity = 0.0,
                            StockId = 1
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "",
                            BarcodeText = "",
                            CategoryName = "Hygiene",
                            Deleted = false,
                            MeasuringUnit = "Units",
                            Name = "Soap",
                            Price = 3f,
                            Quantity = 0.0,
                            StockId = 1
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.ProductShopIntertable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductShopIntertables");
                });

            modelBuilder.Entity("SET3_Backend.Models.ProductUserOrderIntertable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("UserOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductUserOrderIntertables");
                });

            modelBuilder.Entity("SET3_Backend.Models.Racun", b =>
                {
                    b.Property<string>("IdRacun")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DatVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<double>("IznosUkupno")
                        .HasColumnType("float");

                    b.Property<string>("NacinPlac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OibOper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OznSlijed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("USustPdv")
                        .HasColumnType("bit");

                    b.Property<string>("ZastKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brojRacunaIdRac")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdRacun");

                    b.HasIndex("brojRacunaIdRac");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("SET3_Backend.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("DeleteAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("ReadAccess")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WriteAccess")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RoleModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeleteAccess = false,
                            ReadAccess = true,
                            RoleName = "User",
                            WriteAccess = false
                        },
                        new
                        {
                            Id = 2,
                            DeleteAccess = true,
                            ReadAccess = true,
                            RoleName = "Admin",
                            WriteAccess = true
                        },
                        new
                        {
                            Id = 3,
                            DeleteAccess = true,
                            ReadAccess = true,
                            RoleName = "ShopAdmin",
                            WriteAccess = true
                        },
                        new
                        {
                            Id = 4,
                            DeleteAccess = true,
                            ReadAccess = true,
                            RoleName = "StockAdmin",
                            WriteAccess = true
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.SecurityQuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecurityQuestionModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Question = "What is your favourite animal?"
                        },
                        new
                        {
                            Id = 2,
                            Question = "What is your favourite color?"
                        },
                        new
                        {
                            Id = 3,
                            Question = "What is your mothers name?"
                        },
                        new
                        {
                            Id = 4,
                            Question = "What is your dream destination?"
                        },
                        new
                        {
                            Id = 5,
                            Question = "What is your dream car?"
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShopModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Dzemala Bijedica St 160 71000 Sarajevo ",
                            Deleted = false,
                            Name = "Bingo",
                            ReceiptType = "Bosanski",
                            StockId = 1
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Hercegovacka ul. 78 21000 Split Croatia",
                            Deleted = false,
                            Name = "Konzum",
                            ReceiptType = "Hrvatski",
                            StockId = 1
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.StockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warehouse"
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.TableModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<bool>("Taken")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TableModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Unit 1",
                            ShopId = 1,
                            Taken = false
                        },
                        new
                        {
                            Id = 2,
                            Name = "Unit 2",
                            ShopId = 1,
                            Taken = false
                        },
                        new
                        {
                            Id = 3,
                            Name = "Unit 3",
                            ShopId = 1,
                            Taken = false
                        },
                        new
                        {
                            Id = 4,
                            Name = "Unit 4",
                            ShopId = 1,
                            Taken = false
                        },
                        new
                        {
                            Id = 5,
                            Name = "Unit 5",
                            ShopId = 1,
                            Taken = false
                        },
                        new
                        {
                            Id = 6,
                            Name = "Unit 1",
                            ShopId = 2,
                            Taken = false
                        },
                        new
                        {
                            Id = 7,
                            Name = "Unit 2",
                            ShopId = 2,
                            Taken = false
                        },
                        new
                        {
                            Id = 8,
                            Name = "Unit 3",
                            ShopId = 2,
                            Taken = false
                        },
                        new
                        {
                            Id = 9,
                            Name = "Unit 4",
                            ShopId = 2,
                            Taken = false
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TFA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Odgovor",
                            Deleted = false,
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "^?H??(qQ??o??)'s`=\rj???*?rB?",
                            QuestionId = 1,
                            RoleName = "Admin",
                            TFA = ""
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Odgovor",
                            Deleted = false,
                            Email = "shopAdmin@gmail.com",
                            FirstName = "Shop",
                            LastName = "Admin",
                            Password = "^?H??(qQ??o??)'s`=\rj???*?rB?",
                            QuestionId = 1,
                            RoleName = "ShopAdmin",
                            TFA = ""
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Odgovor",
                            Deleted = false,
                            Email = "stockAdmin@gmail.com",
                            FirstName = "Stock",
                            LastName = "Admin",
                            Password = "^?H??(qQ??o??)'s`=\rj???*?rB?",
                            QuestionId = 1,
                            RoleName = "StockAdmin",
                            TFA = ""
                        });
                });

            modelBuilder.Entity("SET3_Backend.Models.UserOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CashRegisterId")
                        .HasColumnType("int");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOrderModels");
                });

            modelBuilder.Entity("SET3_Backend.Models.Zaglavlje", b =>
                {
                    b.Property<string>("IdZag")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DatumVrijeme")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdPoruke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdZag");

                    b.ToTable("Zaglavlje");
                });

            modelBuilder.Entity("SET3_Backend.Models.FiscalBillModel", b =>
                {
                    b.HasOne("SET3_Backend.Models.Racun", "Racun")
                        .WithMany()
                        .HasForeignKey("RacunIdRacun")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET3_Backend.Models.Zaglavlje", "Zaglavlje")
                        .WithMany()
                        .HasForeignKey("ZaglavljeIdZag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racun");

                    b.Navigation("Zaglavlje");
                });

            modelBuilder.Entity("SET3_Backend.Models.LoggingModel", b =>
                {
                    b.HasOne("SET3_Backend.Models.ActionModel", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SET3_Backend.Models.UserModel", "UserModel")
                        .WithMany()
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("SET3_Backend.Models.Porez", b =>
                {
                    b.HasOne("SET3_Backend.Models.Racun", null)
                        .WithMany("pDV")
                        .HasForeignKey("RacunIdRacun");
                });

            modelBuilder.Entity("SET3_Backend.Models.Racun", b =>
                {
                    b.HasOne("SET3_Backend.Models.BrRac", "brojRacuna")
                        .WithMany()
                        .HasForeignKey("brojRacunaIdRac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brojRacuna");
                });

            modelBuilder.Entity("SET3_Backend.Models.Racun", b =>
                {
                    b.Navigation("pDV");
                });
#pragma warning restore 612, 618
        }
    }
}
