version: '3.9'

services:
  set3-frontend:
    build: ./SET3-Frontend/
    container_name: SET3-Frontend
    environment:
      - REACT_APP_BACKEND_URL=https://set3-back.azurewebsites.net/
    restart: always
    ports:
      - 3000:3000
  